SELECT B.YEAR, ABS(B.MAX_SIZE - A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID
FROM ECOLI_DATA AS A
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
     FROM ECOLI_DATA
     GROUP BY YEAR) AS B
ON B.YEAR=YEAR(A.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV