SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO AS A
JOIN FISH_NAME_INFO AS B
ON A.FISH_TYPE=B.FISH_TYPE
JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
     FROM FISH_INFO
     GROUP BY FISH_TYPE) AS C
ON C.FISH_TYPE=A.FISH_TYPE AND C.LENGTH=A.LENGTH
ORDER BY ID